server.port=9000
cors.allowed-origins=http://localhost:3000

# ============================================================
# configuración base de datos
# ============================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/immuneapp
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ============================================================
# ============================================================

# ============================================================
# configuración jwt
# ============================================================

# Clave secreta para la firma del JWT
# todo meter esta clave en variable de entorno para PRO
jwt.secret=BabyNoMeLlameQjdksajkdsakldsajkdjaskdjkslajdksajdklasjdklasjklsdadk

# Tiempo de expiración del token de acceso en milisegundos (por ejemplo, 1 hora)
jwt.expiration=3600000

# Tiempo de expiración del refresh token en milisegundos (por ejemplo, 7 días)
jwt.refreshExpiration=604800000


